services:
  # MySQL Database
  db_pdti:
    container_name: db_pdti
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3307:${DB_PORT} # optional, remove if you want internal-only
    networks:
      - pdti_networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  # phpMyAdmin (internal, accessed via Nginx)
  php-my-admin:
    container_name: php-my-admin
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_ARBITRARY: 1
    expose:
      - "80" # internal only
    networks:
      - pdti_networks

  # Backend
  pdti-backend:
    container_name: pdti-backend
    stdin_open: true
    tty: true
    command: sh -c "yarn start" # Run only main process in foreground
    restart: always
    build:
      context: ./pdti_backend
      dockerfile: Dockerfile
    expose:
      - "${API_PORT}" # internal, Nginx will proxy
    depends_on:
      db_pdti:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - pdti_networks

  # Frontend
  pdti-frontend:
    container_name: pdti-frontend
    build:
      context: ./pdti_frontend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "${FRONTEND_PORT}" # internal, Nginx will proxy
    depends_on:
      - pdti-backend
    networks:
      - pdti_networks

  # Nginx Reverse Proxy
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt # For SSL
    depends_on:
      - pdti-backend
      - pdti-frontend
      - php-my-admin
    networks:
      - pdti_networks

networks:
  pdti_networks:
    driver: bridge
